### ISSUE TITLE
The number of calling 'toggleCtrlPin'

### ISSUE THREAD

**Issue by KeunwooPark** [yangz3/Teensy3.2_Config_AD5930#1]
I tested Teensy_AD5930.ino with Arduino Mega.
Signal didn't come out when I just ran the code, but when I called 'toggleCtrlPin' twice, I could see the signal. As I understand, the current code only runs 'toogleCtrlPin' only once. 

I read the datasheet of AD5930 and it says
![image](https://user-images.githubusercontent.com/1640277/65885091-f258f980-e3d4-11e9-8179-7d893dae3549.png)
in page 21.

My understanding is that the ctrl pin has to be toggled first to start the frequency sweep and toggled again for the frequency increment. Even though the incrementation is 0 in this case.

So if anyone tries this code and it doesn't work, try toggling the ctrl pin twice. It worked for me.

**Comment by yangz3** [comment]
Thanks for sharing what you found.
